component output="false" {
  public numeric function record(required struct input, required struct slideSpec, required struct metrics, required array stages, required struct renderResult){
    var jobId = 0;
    if(!application.enableDb) return jobId;

    try {
      ensureSchema();

      var insertedJob = queryExecute("
        INSERT INTO ppt_jobs(input_json, quality_mode, theme_name, status, output_file, created_at)
        VALUES(:input, :mode, :theme, :status, :output_file, CURRENT_TIMESTAMP)
        RETURNING job_id
      ", {
        input:{value:serializeJSON(arguments.input), cfsqltype:"cf_sql_longvarchar"},
        mode:{value:arguments.metrics.mode, cfsqltype:"cf_sql_varchar"},
        theme:{value:arguments.metrics.theme, cfsqltype:"cf_sql_varchar"},
        status:{value:"completed", cfsqltype:"cf_sql_varchar"},
        output_file:{value:arguments.renderResult.file_name, cfsqltype:"cf_sql_varchar"}
      }, {datasource:application.dsn});

      jobId = val(insertedJob.job_id[1]);

      for(var stageIndex=1; stageIndex<=arrayLen(arguments.stages); stageIndex++){
        var stage = arguments.stages[stageIndex];
        queryExecute("
          INSERT INTO ppt_runs(job_id, stage_name, stage_status, stage_summary, completed_at)
          VALUES(:job, :name, :status, :summary, CURRENT_TIMESTAMP)
        ", {
          job:{value:jobId, cfsqltype:"cf_sql_integer"},
          name:{value:stage.name, cfsqltype:"cf_sql_varchar"},
          status:{value:stage.status, cfsqltype:"cf_sql_varchar"},
          summary:{value:stage.summary, cfsqltype:"cf_sql_varchar"}
        }, {datasource:application.dsn});
      }

      for(var slideIndex=1; slideIndex<=arrayLen(arguments.slideSpec.slides); slideIndex++){
        var slide = arguments.slideSpec.slides[slideIndex];
        queryExecute("
          INSERT INTO ppt_slides(job_id, slide_number, slide_title, layout_name, slide_json, created_at)
          VALUES(:job, :num, :title, :layout, :json, CURRENT_TIMESTAMP)
        ", {
          job:{value:jobId, cfsqltype:"cf_sql_integer"},
          num:{value:slide.slide_number, cfsqltype:"cf_sql_integer"},
          title:{value:slide.title, cfsqltype:"cf_sql_varchar"},
          layout:{value:slide.layout, cfsqltype:"cf_sql_varchar"},
          json:{value:serializeJSON(slide), cfsqltype:"cf_sql_longvarchar"}
        }, {datasource:application.dsn});
      }

      queryExecute("
        INSERT INTO ppt_metrics(
          job_id, prompt_tokens, completion_tokens, estimated_cost, execution_ms,
          planning_ms, rendering_ms, validation_ms, slide_count, model_name,
          theme_name, output_size, created_at
        )
        VALUES(
          :job, :pt, :ct, :cost, :exec,
          :plan, :render, :valid, :slides, :model,
          :theme, :size, CURRENT_TIMESTAMP
        )
      ", {
        job:{value:jobId, cfsqltype:"cf_sql_integer"},
        pt:{value:arguments.metrics.prompt_tokens, cfsqltype:"cf_sql_integer"},
        ct:{value:arguments.metrics.completion_tokens, cfsqltype:"cf_sql_integer"},
        cost:{value:arguments.metrics.estimated_cost, cfsqltype:"cf_sql_decimal"},
        exec:{value:arguments.metrics.execution_ms, cfsqltype:"cf_sql_integer"},
        plan:{value:arguments.metrics.planning_ms, cfsqltype:"cf_sql_integer"},
        render:{value:arguments.metrics.rendering_ms, cfsqltype:"cf_sql_integer"},
        valid:{value:arguments.metrics.validation_ms, cfsqltype:"cf_sql_integer"},
        slides:{value:arguments.metrics.slide_count, cfsqltype:"cf_sql_integer"},
        model:{value:arguments.metrics.model, cfsqltype:"cf_sql_varchar"},
        theme:{value:arguments.metrics.theme, cfsqltype:"cf_sql_varchar"},
        size:{value:arguments.metrics.output_size, cfsqltype:"cf_sql_integer"}
      }, {datasource:application.dsn});
    } catch(any ignored){}

    return jobId;
  }

  public void function recordError(required any error, required struct metrics, required array stages){
    if(!application.enableDb) return;
    try {
      ensureSchema();
      queryExecute("
        INSERT INTO ppt_errors(error_stage, error_message, error_detail, created_at)
        VALUES(:stage, :message, :detail, CURRENT_TIMESTAMP)
      ", {
        stage:{value:"Workflow", cfsqltype:"cf_sql_varchar"},
        message:{value:arguments.error.message, cfsqltype:"cf_sql_varchar"},
        detail:{value:arguments.error.detail ?: serializeJSON(arguments.stages), cfsqltype:"cf_sql_longvarchar"}
      }, {datasource:application.dsn});
    } catch(any ignored){}
  }

  private void function ensureSchema(){
    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_jobs (
        job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        input_json TEXT,
        quality_mode VARCHAR(50),
        theme_name VARCHAR(100),
        status VARCHAR(50),
        output_file VARCHAR(500),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_runs (
        run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id INTEGER,
        stage_name VARCHAR(100) NOT NULL,
        stage_status VARCHAR(50) NOT NULL,
        stage_summary VARCHAR(1000),
        started_at TIMESTAMP,
        completed_at TIMESTAMP,
        duration_ms INTEGER
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_slides (
        slide_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id INTEGER,
        slide_number INTEGER NOT NULL,
        slide_title VARCHAR(500),
        layout_name VARCHAR(100),
        slide_json TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_metrics (
        metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id INTEGER,
        prompt_tokens INTEGER,
        completion_tokens INTEGER,
        estimated_cost NUMERIC(18,6),
        execution_ms INTEGER,
        planning_ms INTEGER,
        rendering_ms INTEGER,
        validation_ms INTEGER,
        slide_count INTEGER,
        model_name VARCHAR(100),
        theme_name VARCHAR(100),
        output_size INTEGER,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_errors (
        error_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id INTEGER,
        error_stage VARCHAR(100),
        error_message VARCHAR(1000),
        error_detail TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_themes (
        theme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        theme_key VARCHAR(100) UNIQUE NOT NULL,
        theme_name VARCHAR(100) NOT NULL,
        theme_json TEXT NOT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});

    queryExecute("
      CREATE TABLE IF NOT EXISTS ppt_demo_results (
        demo_result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        demo_name VARCHAR(200) UNIQUE NOT NULL,
        quality_mode VARCHAR(50) NOT NULL,
        slide_count INTEGER NOT NULL,
        duration_ms INTEGER,
        estimated_cost NUMERIC(18,6),
        model_name VARCHAR(100),
        theme_name VARCHAR(100),
        output_file VARCHAR(500),
        evaluation VARCHAR(1000),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    ", {}, {datasource:application.dsn});
  }
}
