-- PostgreSQL schema for database: demo_ppt
-- Create the database first, then run this file against demo_ppt:
--   createdb demo_ppt
--   psql -d demo_ppt -f sql/demo_ppt_schema.sql

CREATE TABLE IF NOT EXISTS ppt_jobs (
  job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  input_json TEXT,
  quality_mode VARCHAR(50),
  theme_name VARCHAR(100),
  status VARCHAR(50),
  output_file VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ppt_runs (
  run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER,
  stage_name VARCHAR(100) NOT NULL,
  stage_status VARCHAR(50) NOT NULL,
  stage_summary VARCHAR(1000),
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  duration_ms INTEGER
);

CREATE TABLE IF NOT EXISTS ppt_slides (
  slide_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER,
  slide_number INTEGER NOT NULL,
  slide_title VARCHAR(500),
  layout_name VARCHAR(100),
  slide_json TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ppt_metrics (
  metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  estimated_cost NUMERIC(18,6),
  execution_ms INTEGER,
  planning_ms INTEGER,
  rendering_ms INTEGER,
  validation_ms INTEGER,
  slide_count INTEGER,
  model_name VARCHAR(100),
  theme_name VARCHAR(100),
  output_size INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ppt_errors (
  error_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER,
  error_stage VARCHAR(100),
  error_message VARCHAR(1000),
  error_detail TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ppt_themes (
  theme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme_key VARCHAR(100) UNIQUE NOT NULL,
  theme_name VARCHAR(100) NOT NULL,
  theme_json TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ppt_demo_results (
  demo_result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demo_name VARCHAR(200) UNIQUE NOT NULL,
  quality_mode VARCHAR(50) NOT NULL,
  slide_count INTEGER NOT NULL,
  duration_ms INTEGER,
  estimated_cost NUMERIC(18,6),
  model_name VARCHAR(100),
  theme_name VARCHAR(100),
  output_file VARCHAR(500),
  evaluation VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ppt_themes(theme_key, theme_name, theme_json)
VALUES
  ('executive_dark', 'Executive Dark', '{"background":"0B1220","primary":"38BDF8","accent":"22C55E","text":"F8FAFC"}'),
  ('education_light', 'Education Light', '{"background":"F8FAFC","primary":"2563EB","accent":"16A34A","text":"0F172A"}'),
  ('minimal_white', 'Minimal White', '{"background":"FFFFFF","primary":"111827","accent":"2563EB","text":"111827"}'),
  ('coffee_warm', 'Coffee Warm', '{"background":"FBF7F0","primary":"7C2D12","accent":"B45309","text":"1C1917"}'),
  ('travel_editorial', 'Travel Editorial', '{"background":"F0F9FF","primary":"0369A1","accent":"F97316","text":"0C4A6E"}')
ON CONFLICT (theme_key) DO NOTHING;

INSERT INTO ppt_demo_results(
  demo_name, quality_mode, slide_count, duration_ms, estimated_cost,
  model_name, theme_name, output_file, evaluation
)
VALUES
  ('Enterprise AI Strategy', 'balanced', 26, 1850, 0.042000, 'structured-planner-v1', 'executive_dark', 'demo_enterprise_ai_strategy.pptx', 'Pass: required narrative sections present.'),
  ('Medical Operations Briefing', 'beauty', 30, 2420, 0.066000, 'structured-planner-v1', 'education_light', 'demo_medical_operations.pptx', 'Pass: visual rhythm and validation stages complete.'),
  ('Investor Update', 'balanced', 26, 1730, 0.039000, 'structured-planner-v1', 'minimal_white', 'demo_investor_update.pptx', 'Pass: clear executive summary and metrics.'),
  ('Product Launch Plan', 'beauty', 30, 2680, 0.071000, 'structured-planner-v1', 'travel_editorial', 'demo_product_launch.pptx', 'Pass: examples and comparison slides included.'),
  ('Education Workshop', 'balanced', 26, 1660, 0.036000, 'structured-planner-v1', 'education_light', 'demo_education_workshop.pptx', 'Pass: teaching flow is complete.'),
  ('Operational Review', 'balanced', 26, 1780, 0.040000, 'structured-planner-v1', 'executive_dark', 'demo_operational_review.pptx', 'Pass: agenda to closing structure validated.'),
  ('Coffee Brand Story', 'beauty', 30, 2510, 0.068000, 'structured-planner-v1', 'coffee_warm', 'demo_coffee_brand.pptx', 'Pass: warm editorial style and closing included.'),
  ('Travel Market Analysis', 'beauty', 30, 2575, 0.069000, 'structured-planner-v1', 'travel_editorial', 'demo_travel_market.pptx', 'Pass: visual section and comparisons included.'),
  ('AI Governance Brief', 'balanced', 26, 1890, 0.043000, 'structured-planner-v1', 'minimal_white', 'demo_ai_governance.pptx', 'Pass: risk framing and traceability included.'),
  ('Customer Success Plan', 'balanced', 26, 1815, 0.041000, 'structured-planner-v1', 'education_light', 'demo_customer_success.pptx', 'Pass: framework, examples and summary complete.')
ON CONFLICT DO NOTHING;
